# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OmVhdoBAvDfjxCCj0rANfNyy9YMFLCjj
"""

from google.colab import drive
import os
drive.mount('/content/gdrive')

!pip install transformers
!pip install tensorboardx
!pip install simpletransformers

import pandas as pd
import csv 
from google.colab import files
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from simpletransformers.model import TransformerModel
from sklearn.model_selection import train_test_split
df = pd.read_csv('gdrive/My Drive/trainingdata_fix.csv', encoding="latin")
train,test = train_test_split(df,test_size=0.2,random_state=18) #dataframe split
results = []
n = 5                              #KFold times
kf = KFold(n_splits=n, random_state=55688, shuffle=True) 
for train_index, val_index in kf.split(train):
  train_df= train.iloc[train_index]
  val_df = train.iloc[val_index]                          
  label_list = ["0","1","2"]      
  model = TransformerModel('xlnet','xlnet-base-cased',num_labels=3,args={"save_model_every_epoch":False,'overwrite_output_dir':True,
                'learning_rate':1e-5,'num_train_epochs':20,'train_batch_size':32,'output_dir': 'gdrive/My Drive/outputs/'})
  model.train_model(train_df)
  result, model_outputs, wrong_predictions = model.eval_model(val_df,acc=accuracy_score)
  print(result['acc'])
  results.append(result['acc'])
print("results",results)
print(f"Mean-Precision: {sum(results) / len(results)}")